//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Arrest
    {
        public int IDArrest { get; set; }
        public int IDSuspect { get; set; }
        public int IDEmployee { get; set; }
        public int IDCase { get; set; }
        public System.DateTime ArrestDateTime { get; set; }
        public string ArrestCity { get; set; }
        public string ArrestLocation { get; set; }
        public string DecriptionArrest { get; set; }
    
        public virtual Cases Cases { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Suspects Suspects { get; set; }
    }
}
