//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVD.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BazaDan : DbContext
    {
        public BazaDan()
            : base("name=BazaDan")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Arrest> Arrest { get; set; }
        public virtual DbSet<Cases> Cases { get; set; }
        public virtual DbSet<CaseStatus> CaseStatus { get; set; }
        public virtual DbSet<CaseType> CaseType { get; set; }
        public virtual DbSet<Crimes> Crimes { get; set; }
        public virtual DbSet<CrimeType> CrimeType { get; set; }
        public virtual DbSet<Departments> Departments { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<EntrancePass> EntrancePass { get; set; }
        public virtual DbSet<Evidence> Evidence { get; set; }
        public virtual DbSet<EvidenceType> EvidenceType { get; set; }
        public virtual DbSet<ForClient> ForClient { get; set; }
        public virtual DbSet<Investigation> Investigation { get; set; }
        public virtual DbSet<InvestigationStatus> InvestigationStatus { get; set; }
        public virtual DbSet<InvestigationType> InvestigationType { get; set; }
        public virtual DbSet<Rol> Rol { get; set; }
        public virtual DbSet<ServiceItems> ServiceItems { get; set; }
        public virtual DbSet<Suspects> Suspects { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Training> Training { get; set; }
        public virtual DbSet<TrainingStatus> TrainingStatus { get; set; }
        public virtual DbSet<TypeUniform> TypeUniform { get; set; }
        public virtual DbSet<Unifrorm> Unifrorm { get; set; }
        public virtual DbSet<Vehicle> Vehicle { get; set; }
        public virtual DbSet<VehicleStatus> VehicleStatus { get; set; }
        public virtual DbSet<VehicleType> VehicleType { get; set; }
        public virtual DbSet<Weapon> Weapon { get; set; }
        public virtual DbSet<WeaponStatus> WeaponStatus { get; set; }
        public virtual DbSet<WeaponType> WeaponType { get; set; }
        public virtual DbSet<Witnesses> Witnesses { get; set; }
    }
}
