//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Crimes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Crimes()
        {
            this.Suspects = new HashSet<Suspects>();
        }
    
        public int IDCrime { get; set; }
        public int IDCrimeType { get; set; }
        public int IDCase { get; set; }
        public string DescriptionCrime { get; set; }
        public string CrimeCity { get; set; }
        public string CrimeLocation { get; set; }
        public Nullable<System.DateTime> CrimeDateTime { get; set; }
    
        public virtual Cases Cases { get; set; }
        public virtual CrimeType CrimeType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Suspects> Suspects { get; set; }
    }
}
