//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVD.Model
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.Arrest = new HashSet<Arrest>();
            this.Cases = new HashSet<Cases>();
            this.Investigation = new HashSet<Investigation>();
            this.ServiceItems = new HashSet<ServiceItems>();
        }
       
        public int IDEmployee { get; set; }
      
        public int IDRol { get; set; }
      
        public Nullable<int> IDDepartments { get; set; }
        [Required(ErrorMessage = "Имя является обязательным полем")]
        [StringLength(34, MinimumLength = 2, ErrorMessage = "Имя должно быть от 2 до 34 символов")]
        public string FirstName { get; set; }
        [Required(ErrorMessage = "Фамилия является обязательным полем")]
        [StringLength(34, MinimumLength = 6, ErrorMessage = "Фамилия должна быть от 6 до 34 символов")]
        public string LastName { get; set; }
        [StringLength(38, ErrorMessage = "Отчество не должно превышать 38 символов")]
        public string LastestName { get; set; }
        [Required(ErrorMessage = "Дата рождения является обязательным полем")]
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        [Required(ErrorMessage = "Номер телефона является обязательным полем")]
        [RegularExpression(@"^\+\d{1,3}\(\d{3}\)\d{3}-\d{2}-\d{2}$", ErrorMessage = "Некорректный формат номера телефона,введите телефон в виде +7(___)___-__-__")]
        public string NumberPhone { get; set; }
        [Required(ErrorMessage = "Адрес электронной почты является обязательным полем")]
        [StringLength(100, MinimumLength = 10, ErrorMessage = "Некорректный формат адреса электронной почты")]
        public string Email { get; set; }
        [Required(ErrorMessage = "Серия паспорта является обязательным полем")]
        [StringLength(4, ErrorMessage = "Серия паспорта не должна превышать 4 символов")]
        public string PasportaSeria { get; set; }
        [Required(ErrorMessage = "Номер паспорта является обязательным полем")]
        [StringLength(6, MinimumLength = 6, ErrorMessage = "Номер паспорта должна состоять из 6 символов")]
        public string PasportNumber { get; set; }
        [Required(ErrorMessage = "Дата начала работы является обязательным полем")]
        public Nullable<System.DateTime> HireDate { get; set; }
        [Required(ErrorMessage = "Зарплата является обязательным полем")]
        [StringLength(20, MinimumLength = 5, ErrorMessage = "Поле зарплата должен быть от 5 до 20 символов")]
        public string Salary { get; set; }
        [Required(ErrorMessage = "Логин является обязательным полем")]
        [StringLength(8, MinimumLength = 3, ErrorMessage = "Логин должен быть от 3 до 8 символов")]
        public string Login { get; set; }
        [Required(ErrorMessage = "Пароль является обязательным полем")]
        [StringLength(65, MinimumLength = 4, ErrorMessage = "Пароль должен быть от 4 до 65 символов")]
        public string Password { get; set; }
       
        public Nullable<int> TwoFactorAvtor { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Arrest> Arrest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cases> Cases { get; set; }
        public virtual Departments Departments { get; set; }
        public virtual Rol Rol { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Investigation> Investigation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceItems> ServiceItems { get; set; }
    }
}
