//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Evidence
    {
        public int IDEvidence { get; set; }
        public int IDEvidenceType { get; set; }
        public int IDCase { get; set; }
        public string DescriptionEvidence { get; set; }
        public string EvidenceLocation { get; set; }
        public System.DateTime CollectionDate { get; set; }
    
        public virtual Cases Cases { get; set; }
        public virtual EvidenceType EvidenceType { get; set; }
    }
}
