//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ForClient
    {
        public int IDClient { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string LastestName { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public string NumberPhone { get; set; }
        public string PasportaSeria { get; set; }
        public string PasportNumber { get; set; }
        public string Statment { get; set; }
    }
}
