//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Training
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Training()
        {
            this.ServiceItems = new HashSet<ServiceItems>();
        }
    
        public int IDTraining { get; set; }
        public int IDTrainingStatus { get; set; }
        public string TrainingNmae { get; set; }
        public string Description { get; set; }
        public System.DateTime TrainingDate { get; set; }
        public string TrainingCity { get; set; }
        public string TrainingLocation { get; set; }
        public int NumberOfSeats { get; set; }
        public string Duration { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceItems> ServiceItems { get; set; }
        public virtual TrainingStatus TrainingStatus { get; set; }
    }
}
