//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Unifrorm
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Unifrorm()
        {
            this.ServiceItems = new HashSet<ServiceItems>();
        }
    
        public int IDUniform { get; set; }
        public int IDTypeUniform { get; set; }
        public string Description { get; set; }
        public string SerialNumber { get; set; }
        public System.DateTime DateOfIssues { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceItems> ServiceItems { get; set; }
        public virtual TypeUniform TypeUniform { get; set; }
    }
}
