//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vehicle()
        {
            this.ServiceItems = new HashSet<ServiceItems>();
        }
    
        public int IDVehicle { get; set; }
        public int IDVehicleType { get; set; }
        public int IDVehicleStatus { get; set; }
        public string CarBrand { get; set; }
        public string Model { get; set; }
        public string NumberOfPlace { get; set; }
        public string SerialNumber { get; set; }
        public System.DateTime DateOfIssues { get; set; }
        public string CarNumber { get; set; }
        public int CarRegionNumber { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceItems> ServiceItems { get; set; }
        public virtual VehicleStatus VehicleStatus { get; set; }
        public virtual VehicleType VehicleType { get; set; }
    }
}
